# Generated by Django 5.2 on 2025-05-01 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paradas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Ruta')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción de la Ruta')),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('distancia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código de la Ruta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
            },
        ),
        migrations.CreateModel(
            name='RutaParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(verbose_name='Orden de la Parada')),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas_rutas', to='paradas.paradas')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_paradas', to='rutas.ruta')),
            ],
            options={
                'verbose_name': 'Ruta-Parada',
                'verbose_name_plural': 'Rutas-Paradas',
                'ordering': ['orden'],
                'unique_together': {('ruta', 'orden')},
            },
        ),
    ]
