# Generated by Django 5.2 on 2025-05-01 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UltimaUbicacionAutobus',
            fields=[
                ('autobus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ultima_ubicacion', serialize=False, to='usuarios.conductor')),
                ('latitud', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Longitud')),
                ('fecha_hora', models.DateTimeField(auto_now=True, verbose_name='Fecha y Hora')),
            ],
            options={
                'verbose_name': 'Última Ubicación de Autobús',
                'verbose_name_plural': 'Últimas Ubicaciones de Autobús',
            },
        ),
    ]
